env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  max-len: [1, 80, 2],
  "react/react-in-jsx-scope": "off",
  "import/prefer-default-export": "off",
  "require-jsdoc": "off"
}
