FROM node:14.14.0-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json /app
COPY package-lock.json /app
COPY next.config.js /app

RUN npm install
RUN npm install -g next-translate

COPY . /app

RUN npm run build
EXPOSE 3000

ENTRYPOINT ["npm", "run", "dev"]
