FROM node:14.14.0-alpine


RUN apk update
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app

RUN npm install
RUN npm install -g nodemon

COPY . /app

RUN mkdir -p /app/static

EXPOSE 4001

ENTRYPOINT ["npm", "run", "dev"]
